# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G732suGc-k9oduMMRQReh01yZni-MTT-
"""

!pip install streamlit

import streamlit as st

import re
import pickle

from keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

st.title("AI MBTI Personality Chatbot")

IE_model = load_model("IE_model.h5")

NS_model = load_model("NS_model.h5")

TF_model = load_model("TF_model.h5")

JP_model = load_model("JP_model.h5")

with open('tokenizer.pkl', 'rb') as f:
    tokenizer = pickle.load(f)

max_len = 200

def clean_text(text):

    text = text.lower()

    text = re.sub(r'http\S+', '', text)

    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    text = re.sub(r'\s+', ' ', text).strip()

    return text

def predict_mbti(text):

    # clean text
    text = clean_text(text)

    # convert text to sequence
    seq = tokenizer.texts_to_sequences([text])

    # pad sequence
    padded = pad_sequences(
        seq,
        maxlen=max_len,
        padding='post',
        truncating='post'
    )

    # predictions
    IE_pred = IE_model.predict(padded)[0][0]

    NS_pred = NS_model.predict(padded)[0][0]

    TF_pred = TF_model.predict(padded)[0][0]

    JP_pred = JP_model.predict(padded)[0][0]

    # probabilities to letters
    ie = 'E' if IE_pred >= 0.1 else 'I'

    ns = 'S' if NS_pred >= 0.1 else 'N'

    tf = 'F' if TF_pred >= 0.1 else 'T'

    jp = 'P' if JP_pred >= 0.1 else 'J'

    # final mbti
    mbti = ie + ns + tf + jp

    return mbti

questions = [

    "How do you usually spend your weekends?",

    "What kind of social situations make you comfortable?",

    "How do you make important decisions?",

    "Do you prefer planning things or being spontaneous?",

    "How do you react after a stressful day?",

    "Would you rather work alone or in a team?",

    "Do you enjoy practical work or theoretical ideas more?",

    "How do you prepare before important events?",

    "What type of conversations do you enjoy the most?",

    "What motivates you the most in life?"
]

responses = []

print("===== MBTI Personality Chatbot =====\n")

for q in questions:

    ans = input(q + "\n\nYou: ")

    responses.append(ans)

    print()

full_text = " ".join(responses)

result = predict_mbti(full_text)

print("\n===== FINAL PERSONALITY RESULT =====")

print("\nPredicted MBTI Type:", result)

